# Generated by Django 4.0 on 2022-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfaAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Название поста')),
                ('text', models.TextField(default=None, max_length=1000, verbose_name='Текст поста')),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('dateOfChenges', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Параграф для AboutUs',
                'verbose_name_plural': 'Параграфы для AboutUs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramsInfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Имя программы')),
                ('text', models.TextField(default=None, max_length=1000, verbose_name='Краткое описание программы')),
                ('image', models.ImageField(default=None, upload_to='imagesForDocumentation/', verbose_name='Иконка программы')),
                ('link1', models.CharField(default=None, max_length=100, verbose_name='Первая ссылка программы')),
                ('nameOfLink1', models.CharField(default=None, max_length=50, verbose_name='Название первой ссылки программы')),
                ('link2', models.CharField(default=None, max_length=100, verbose_name='Вторая ссылка программы')),
                ('nameOfLink2', models.CharField(default=None, max_length=50, verbose_name='Название второй ссылки программы')),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('dateOfChenges', models.DateField(auto_now=True)),
                ('colorL', models.CharField(default='blue', max_length=20, verbose_name='Цвет ссылок')),
                ('colorBG', models.CharField(default='white', max_length=20, verbose_name='Цвет фона')),
                ('colorN', models.CharField(default='black', max_length=20, verbose_name='Цвет имени программы')),
                ('colorT', models.CharField(default='black', max_length=20, verbose_name='Цвет краткого описания')),
            ],
            options={
                'verbose_name': 'Программа для Documentation',
                'verbose_name_plural': 'Программы для Documentation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Redic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarRedirect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoOurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Название видео')),
                ('video', models.FileField(default=None, upload_to='videoForOurWorks/', verbose_name='Видео(ваша работа)')),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('dateOfChenges', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Видео для OurWorks',
                'verbose_name_plural': 'Видео для OurWorks',
                'ordering': ['id'],
            },
        ),
    ]
