# Generated by Django 4.0 on 2022-03-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsinfa',
            name='colorBG',
        ),
        migrations.RemoveField(
            model_name='programsinfa',
            name='colorL',
        ),
        migrations.RemoveField(
            model_name='programsinfa',
            name='colorN',
        ),
        migrations.RemoveField(
            model_name='programsinfa',
            name='colorT',
        ),
    ]
