# Generated by Django 4.0 on 2022-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0002_infaaboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infaaboutus',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='infaaboutus',
            name='name',
            field=models.CharField(default='SOME NAME', max_length=50),
        ),
        migrations.AddField(
            model_name='infaaboutus',
            name='text',
            field=models.TextField(default='SOME TEXT', max_length=500),
        ),
    ]
