# Generated by Django 4.0 on 2022-03-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0002_remove_programsinfa_colorbg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsinfa',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='programsinfa',
            name='nameOfLink2',
        ),
    ]
