# Generated by Django 4.0 on 2022-03-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0003_remove_programsinfa_link2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='We',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Имя программы')),
                ('vk', models.CharField(default=None, max_length=100, verbose_name='Ссылка на соц. сеть')),
                ('foto', models.ImageField(default=None, upload_to='fotoWe/', verbose_name='Ваше фото')),
            ],
            options={
                'verbose_name': 'Вы',
                'verbose_name_plural': 'Вы',
                'ordering': ['id'],
            },
        ),
    ]
