# Generated by Django 4.0 on 2022-03-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0003_remove_infaaboutus_paragraph_infaaboutus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infaaboutus',
            options={'ordering': ['id'], 'verbose_name': 'Параграф для AboutUs', 'verbose_name_plural': 'Параграфы для AboutUs'},
        ),
    ]
