# Generated by Django 4.0 on 2022-03-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0004_alter_infaaboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesOurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME NAME', max_length=50)),
                ('image', models.ImageField(upload_to='imagesForOurWorks/')),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('dateOfChenges', models.DateField(auto_now=True)),
            ],
        ),
    ]
