# Generated by Django 4.0 on 2022-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0004_we'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='we',
            options={'ordering': ['id'], 'verbose_name': 'Вы', 'verbose_name_plural': 'вас'},
        ),
        migrations.AlterField(
            model_name='we',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Ваше имя'),
        ),
    ]
