# Generated by Django 4.0 on 2022-03-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0005_imagesourworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesourworks',
            options={'ordering': ['id'], 'verbose_name': 'Фото для OurWorks', 'verbose_name_plural': 'Фотографии для OurWorks'},
        ),
    ]
