# Generated by Django 4.0 on 2022-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0005_alter_we_options_alter_we_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfModeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Вид моделирования')),
                ('number', models.IntegerField(default=None, max_length=20, verbose_name='Кол-во проголосовавших')),
            ],
            options={
                'verbose_name': 'Тип модели',
                'verbose_name_plural': 'Типы моделей',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='we',
            options={'ordering': ['id'], 'verbose_name': 'Вы', 'verbose_name_plural': 'Вас'},
        ),
    ]
