# Generated by Django 4.0 on 2022-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0006_typeofmodeling_alter_we_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofmodeling',
            name='number',
            field=models.IntegerField(default=None, verbose_name='Кол-во проголосовавших'),
        ),
    ]
