# Generated by Django 4.0 on 2022-03-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0007_alter_typeofmodeling_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofmodeling',
            options={'ordering': ['id'], 'verbose_name': 'Тип моделирования', 'verbose_name_plural': 'Типы моделирования'},
        ),
    ]
