# Generated by Django 4.0 on 2022-04-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0009_answerstable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerstable',
            old_name='answer',
            new_name='answer5',
        ),
        migrations.AddField(
            model_name='answerstable',
            name='answer1',
            field=models.CharField(default=None, max_length=100, verbose_name='ответ 1'),
        ),
        migrations.AddField(
            model_name='answerstable',
            name='answer2',
            field=models.CharField(default=None, max_length=100, verbose_name='ответ 2'),
        ),
        migrations.AddField(
            model_name='answerstable',
            name='answer3',
            field=models.CharField(default=None, max_length=100, verbose_name='ответ 3'),
        ),
        migrations.AddField(
            model_name='answerstable',
            name='answer4',
            field=models.CharField(default=None, max_length=100, verbose_name='ответ 4'),
        ),
    ]
