# Generated by Django 4.0 on 2022-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0010_rename_answer_answerstable_answer5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerstable',
            name='answer1',
            field=models.CharField(blank=True, max_length=100, verbose_name='ответ 1'),
        ),
        migrations.AlterField(
            model_name='answerstable',
            name='answer2',
            field=models.CharField(blank=True, max_length=100, verbose_name='ответ 2'),
        ),
        migrations.AlterField(
            model_name='answerstable',
            name='answer3',
            field=models.CharField(blank=True, max_length=100, verbose_name='ответ 3'),
        ),
        migrations.AlterField(
            model_name='answerstable',
            name='answer4',
            field=models.CharField(blank=True, max_length=100, verbose_name='ответ 4'),
        ),
        migrations.AlterField(
            model_name='answerstable',
            name='answer5',
            field=models.CharField(blank=True, max_length=100, verbose_name='ответ 5'),
        ),
    ]
