# Generated by Django 4.0 on 2022-04-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0011_alter_answerstable_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.CharField(default='PC, Laptop, Phone', max_length=100)),
                ('cost', models.CharField(default='Free, Laptop, Smartphone', max_length=100)),
                ('using', models.CharField(default='Series, VideoGames, Models', max_length=100)),
                ('typeOfModeling', models.CharField(default='Solid, Polygonal, Sculpting', max_length=100)),
                ('experience', models.CharField(default='Deep, Surface', max_length=100)),
                ('prefabs', models.CharField(default='Help, Yourself', max_length=100)),
            ],
            options={
                'verbose_name': 'Настройки Программы',
                'verbose_name_plural': 'Настройки Программ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramsForBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Какое-то имя программы', max_length=100)),
                ('settingsOfProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_page.programsettings')),
            ],
            options={
                'verbose_name': 'Программа для бота',
                'verbose_name_plural': 'Программы для бота',
                'ordering': ['id'],
            },
        ),
    ]
