# Generated by Django 4.0 on 2022-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0012_programsettings_programsforbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='forWho',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
