# Generated by Django 4.0 on 2022-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0013_programsettings_forwho'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programsettings',
            name='cost',
            field=models.CharField(default='Free, Pay', max_length=100),
        ),
    ]
