# Generated by Django 4.0 on 2022-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0015_alter_programsettings_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsettings',
            name='typeOfModeling',
            field=models.CharField(default='Solid, Polygonal, Sculpting', max_length=100, verbose_name='Какие типы моделирования используются'),
        ),
    ]
