# Generated by Django 4.0 on 2022-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0017_programsettings_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsforbot',
            name='description',
            field=models.CharField(default='описание', max_length=1000, verbose_name='Описание программы'),
        ),
    ]
