# Generated by Django 4.0 on 2022-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0019_alter_programsforbot_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50, verbose_name='Имя пользователя')),
                ('second_name', models.CharField(default=None, max_length=50, verbose_name='Фамилия пользователя')),
                ('choise', models.TextField(default=None, max_length=500, verbose_name='Список данных')),
            ],
            options={
                'verbose_name': 'Выбор пользователя',
                'verbose_name_plural': 'Выборы пользователей',
                'ordering': ['id'],
            },
        ),
    ]
