# Generated by Django 4.0 on 2022-04-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0020_choiseofuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiseofuser',
            name='id_of_user',
            field=models.CharField(default=None, max_length=100, verbose_name='Айди пользователя'),
        ),
    ]
